// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.

namespace Xamarin.MobileWorld
{
    public static class BaseAddress
    {
        public static string BaseApiEndpoint
        {
            get { return "http://localhost:8080/"; }
        }
    }
}
